

DROP TABLE KEYSEARCH;

CREATE TABLE KEYSEARCH(
	M_ID VARCHAR(1000) NOT NULL,
	M_SEARCH VARCHAR(4000) NOT NULL,
	CONSTRAINTS M_ID_FK FOREIGN KEY(M_ID) REFERENCES MYMEMBER(M_ID) 
);

SELECT * FROM KEYSEARCH;

SELECT * FROM KEYSEARCH WHERE M_ID = 'KIM';
INSERT INTO KEYSEARCH VALUES('KIM', '군산맛집');
INSERT INTO KEYSEARCH VALUES('KIM', '이천맛집');



SELECT M_SEARCH, COUNT(*) AS 검색개수 FROM KEYSEARCH WHERE M_ID='KIM' GROUP BY M_SEARCH ORDER BY 검색개수 DESC;

SELECT ROWNUM, A.*
FROM( SELECT M_SEARCH, COUNT(*) AS 검색개수 FROM KEYSEARCH WHERE M_ID='KIM' GROUP BY M_SEARCH ORDER BY 검색개수 DESC ) A
WHERE ROWNUM<=3;








